package com.example.devso.entity.recruit;

public enum TechStack {
    JAVASCRIPT, TYPESCRIPT, REACT, VUE, NODEJS, SPRING, JAVA, JPA,
    NEXTJS, NESTJS, EXPRESS, GO, C, PYTHON, DJANGO, SWIFT, KOTLIN,
    MYSQL, MONGODB, PHP, GRAPHQL, FIREBASE, REACTNATIVE, UNITY, FLUTTER,
    AWS, KUBERNETES, DOCKER, GIT, FIGMA, ZEPLIN, JEST, SVELTE;
}
